import {
  File,
  FileText,
  FileCheck,
  FileCode,
  FileSpreadsheet,
  Book,
  BookOpen,
  Notebook,
  Clipboard,
  ClipboardList,
  Scroll,
  Newspaper,
  StickyNote,
  PenLine,
  PenTool,
  Highlighter,
  Type,
  AlignLeft,
  List,
  ListChecks,
  CheckCircle,
  CircleDot,
  Calendar,
  Clock,
  Timer,
  Briefcase,
  Target,
  Flag,
  Bookmark,
  Tag,
  Inbox,
  Mail,
  Send,
  Phone,
  Video,
  Users,
  User,
  Building,
  MapPin,
  Globe,
  Home,
  Grid3x3,
  LayoutGrid,
  Settings,
  Lock,
  Unlock,
  Link,
  Paperclip,
  Cloud,
  Bell,
  Search,
  Zap,
  Lightbulb,
  Star,
  Heart,
  Shield,
  Key,
  Database,
  Server,
  Code,
} from "lucide-react";

export const ICON_CATEGORIES = {
  documents: [
    "file",
    "file-text",
    "file-check",
    "file-code",
    "file-spreadsheet",
    "book",
    "book-open",
    "notebook",
    "clipboard",
    "clipboard-list",
    "scroll",
    "newspaper",
    "sticky-note",
    "pen-line",
    "pen-tool",
    "highlighter",
    "type",
    "align-left",
    "list",
    "list-checks",
  ],
  work: [
    "check-circle",
    "circle-dot",
    "calendar",
    "clock",
    "timer",
    "briefcase",
    "target",
    "flag",
    "bookmark",
    "tag",
    "inbox",
    "mail",
    "send",
    "phone",
    "video",
    "users",
    "user",
    "building",
    "map-pin",
    "globe",
  ],
  general: [
    "home",
    "grid-3x3",
    "layout-grid",
    "settings",
    "lock",
    "unlock",
    "link",
    "paperclip",
    "cloud",
    "bell",
    "search",
    "zap",
    "lightbulb",
    "star",
    "heart",
    "shield",
    "key",
    "database",
    "server",
    "code",
  ],
};

export const ICON_MAP = {
  file: File,
  "file-text": FileText,
  "file-check": FileCheck,
  "file-code": FileCode,
  "file-spreadsheet": FileSpreadsheet,
  book: Book,
  "book-open": BookOpen,
  notebook: Notebook,
  clipboard: Clipboard,
  "clipboard-list": ClipboardList,
  scroll: Scroll,
  newspaper: Newspaper,
  "sticky-note": StickyNote,
  "pen-line": PenLine,
  "pen-tool": PenTool,
  highlighter: Highlighter,
  type: Type,
  "align-left": AlignLeft,
  list: List,
  "list-checks": ListChecks,
  "check-circle": CheckCircle,
  "circle-dot": CircleDot,
  calendar: Calendar,
  clock: Clock,
  timer: Timer,
  briefcase: Briefcase,
  target: Target,
  flag: Flag,
  bookmark: Bookmark,
  tag: Tag,
  inbox: Inbox,
  mail: Mail,
  send: Send,
  phone: Phone,
  video: Video,
  users: Users,
  user: User,
  building: Building,
  "map-pin": MapPin,
  globe: Globe,
  home: Home,
  "grid-3x3": Grid3x3,
  "layout-grid": LayoutGrid,
  settings: Settings,
  lock: Lock,
  unlock: Unlock,
  link: Link,
  paperclip: Paperclip,
  cloud: Cloud,
  bell: Bell,
  search: Search,
  zap: Zap,
  lightbulb: Lightbulb,
  star: Star,
  heart: Heart,
  shield: Shield,
  key: Key,
  database: Database,
  server: Server,
  code: Code,
};

export const ICON_COLORS = {
  gray: { light: "#9ca3af", dark: "#9ca3af" },
  red: { light: "#ef4444", dark: "#f87171" },
  amber: { light: "#d97706", dark: "#fbbf24" },
  green: { light: "#16a34a", dark: "#4ade80" },
  blue: { light: "#2563eb", dark: "#60a5fa" },
  purple: { light: "#7c3aed", dark: "#a78bfa" },
  pink: { light: "#db2777", dark: "#f472b6" },
};

export const ICON_COLOR_NAMES = Object.keys(ICON_COLORS);

export const ALL_ICON_NAMES = Object.keys(ICON_MAP);

export function getIconComponent(name) {
  return ICON_MAP[name] || File;
}

export function getIconColor(colorName, theme) {
  const color = ICON_COLORS[colorName] || ICON_COLORS.gray;
  return theme === "dark" ? color.dark : color.light;
}
